### ISSUE TITLE
Exception in org.qortal.api.websocket.TradeBotWebSocket

### ISSUE THREAD

**Issue by archived-2** [Qortal/qortal#11]
In qortal 1.3.2 I am regularly getting this exception:

```2020-08-13` 10:36:17 WARN  JettyAnnotatedEventDriver:168 - Unable to report throwable to websocket (no @OnWebSocketError handler declared): org.qortal.api.websocket.TradeBotWebSocket
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 300003/300000 ms
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:567) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:540) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:138) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113) ~[qortal.jar:1.3.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300003/300000 ms
	... 8 more
2020-08-13 10:51:13 WARN  JettyAnnotatedEventDriver:168 - Unable to report throwable to websocket (no @OnWebSocketError handler declared): org.qortal.api.websocket.TradeOffersWebSocket
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 300004/300000 ms
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:567) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:540) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:138) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171) ~[qortal.jar:1.3.2]
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113) ~[qortal.jar:1.3.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300004/300000 ms
	... 8 more```

I have a trade in progress which is stuck in the `ALICE_WATCH_P2SH_B` state, possibly due to issues with the seller's node. it seems that once this exception occurs, my core stops being functional and there are no further logs until it is restarted.

**Comment by catbref** [comment]
At first glance, that looks like a timeout (after 300,000ms) on a websocket not being handled properly.
At worst, that should only cause that one Jetty thread to exit, not affecting anything else.
Will fix the above!

Regarding your trade, maybe you are being affected by issue #14 ?

Thanks!

**Comment by tcallahan14** [comment]
Yes - the issue with my trade did turn out to be #14 - so that part can be ignored.

I'm not sure why my entire node appeared unresponsive, but if it happens again I'll look into it a bit further.

**Comment by IceBurst** [comment]
Issue was corrected in #14
