### ISSUE TITLE
Can't create listen socket.  Protocol family unavailable.

### ISSUE THREAD

**Issue by lifeboy** [Qortal/qortal#25]
OS: Ubuntu 18:04
OpenJDK 11

What causes this?  What protocol is not available?

The machine it pretty much standard and number of Java app are running, like dBeaver for instance,

run.log:
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Gtk-Message: 12:38:08.074: Failed to load module "canberra-gtk-module"
2021-02-07 12:38:09 ERROR Network:158 - Can't create listen socket: Protocol family unavailable
2021-02-07 12:38:09 ERROR Controller:429 - Unable to start networking
java.io.IOException: Can't create listen socket
        at org.qortal.network.Network.start(Network.java:159) ~[qortal.jar:1.4.1]
        at org.qortal.controller.Controller.main(Controller.java:427) [qortal.jar:1.4.1]
Caused by: java.net.SocketException: Protocol family unavailable
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
        at org.qortal.network.Network.start(Network.java:152) ~[qortal.jar:1.4.1]
        ... 1 more

**Comment by lifeboy** [comment]
I have disabled ipv6 because some programs where not functioning properly.  Does Qortal require ipv6?

**Comment by tcallahan14** [comment]
Yes, there does appear to be a dependency on IPv6 right now, at least locally. See line 50 of Settings.java:

```private String bindAddress = "::"; // Use IPv6 wildcard to listen on all local addresses```

I will try and look into this at some point, as it would be good to remove this requirement.

**Comment by tcallahan14** [comment]
You could try binding via IPv4 by putting this in your settings.json:

```{
"bindAddress":"0.0.0.0"
}```

**Comment by tcallahan14** [comment]
Let me know if it works, as if so, I could submit some code to automatically fall back to IPv4.

**Comment by lifeboy** [comment]
Yes, that worked.  It would probably be a god idea to add that fallback.

**Comment by tcallahan14** [comment]
Glad to hear it :) I'll probably give this a go very soon in that case.
