### ISSUE TITLE
java.io.IOException: Can't create listen socket

### ISSUE THREAD

**Issue by DemonRx** [Qortal/qortal#41]
This problem occurs upon running the `start.sh` script.

```java
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-06-10 13:11:36 ERROR Network:148 - Can't create listen socket: Protocol family unavailable
2021-06-10 13:11:36 ERROR Controller:439 - Unable to start networking
java.io.IOException: Can't create listen socket
	at org.qortal.network.Network.start(Network.java:149) ~[qortal.jar:1.5.3]
	at org.qortal.controller.Controller.main(Controller.java:437) [qortal.jar:1.5.3]
Caused by: java.net.SocketException: Protocol family unavailable
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at org.qortal.network.Network.start(Network.java:142) ~[qortal.jar:1.5.3]
	... 1 more
```

**Comment by DemonRx** [comment]
Apparently on linux, openjdk-11-jre package is too old of a version on ubuntu 21.04. I updated to openjdk-17-jre and this solved the problem.

**Comment by CalDescent14** [comment]
Hey, see this issue: https://github.com/Qortal/qortal/issues/25

It can be solved on JDK 11 / 14 by adding this to your settings.json:

`{ "bindAddress":"0.0.0.0" }`

Interesting that JDK 17 fixes it; I'll have to investigate that at some point. There is also an automatic fix for this in the `bindaddress-ipv4` branch, which I may merge into master soon to prevent this problem from happening at all.

**Comment by DemonRx** [comment]
I'll keep this issue open, since it still affects users that keep ipv6 disabled in their network (as I do).

**Comment by IceBurst** [comment]
Ubuntu users should be on v24 LTS or v25, the default JRE installed with those O/S is JRE v21.  This is being closed and marked as completed, over come by events.
