### ISSUE TITLE
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

### ISSUE THREAD

**Issue by DemonRx** [Qortal/qortal#42]
```java
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.nio.channels.UnsupportedAddressTypeException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:161)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:330)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at org.qortal.network.Network.start(Network.java:142)
	at org.qortal.controller.Controller.main(Controller.java:437)
```
Running core version 1.5.3 on Ubuntu 21.04

**Comment by DemonRx** [comment]
Closing per https://github.com/Qortal/qortal/issues/41#issuecomment-858978155
