### ISSUE TITLE
Bootstrapping fails with VPN enabled

### ISSUE THREAD

**Issue by Nuc1eoN** [Qortal/qortal#94]
Bootstrapping fails when I enable my VPN service (tested on both Linux & Windows):

![image](https://user-images.githubusercontent.com/2538022/194646389-2a2c70cf-744e-417e-b04b-7004732ba4ba.png)

Here are the logs:
```
2022-09-24 06:29:14 INFO  Controller:366 - Starting up...
2022-09-24 06:29:14 INFO  Controller:262 - Build timestamp: 20220919162926
2022-09-24 06:29:14 INFO  Controller:274 - Build version: qortal-3.6.0-b99b1f5
2022-09-24 06:29:15 INFO  Settings:431 - Using settings file: settings.json
2022-09-24 06:29:15 INFO  BlockChain:278 - Using default, resources-based blockchain config
2022-09-24 06:29:15 INFO  Controller:262 - Build timestamp: 20220919162926
2022-09-24 06:29:15 INFO  Controller:274 - Build version: qortal-3.6.0-b99b1f5
2022-09-24 06:29:15 INFO  Controller:387 - Starting NTP
2022-09-24 06:29:15 INFO  Controller:394 - Starting repository
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 1
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 2
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 3
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 4
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 5
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 6
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 7
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 8
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 9
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 10
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 11
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 12
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 13
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 14
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 15
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 16
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 17
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 18
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 19
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 20
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 21
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 22
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 23
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 24
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 25
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 26
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 27
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 28
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 29
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 30
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:745 - Rebuilding AT state summaries in repository - this might take a while... (approx. 2 mins on high-spec)
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:756 - Rebuilding AT states height index in repository - this might take about 3x longer...
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:767 - Rebuilding AT state data in repository - this might take a while... (approx. 2 mins on high-spec)
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 31
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 32
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 33
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 34
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:834 - Altering AT table in repository - this might take a while... (approx. 20 seconds on high-spec)
2022-09-24 06:29:15 INFO  HSQLDBDatabaseUpdates:847 - Adding index to AT states table...
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:855 - Altering AT states table in repository - this might take a while... (approx. 3 mins on high-spec)
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 35
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 36
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 37
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 38
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 39
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 40
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 41
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 42
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 43
2022-09-24 06:29:16 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 44
2022-09-24 06:29:16 INFO  HSQLDBRepository:325 - Performing repository CHECKPOINT...
2022-09-24 06:29:16 INFO  HSQLDBRepository:337 - Repository CHECKPOINT completed!
2022-09-24 06:29:16 INFO  HSQLDBDatabaseArchiving:43 - Building block archive - this process could take a while...
2022-09-24 06:29:16 INFO  BlockArchiveWriter:96 - Fetching blocks from height 2...
2022-09-24 06:29:16 INFO  BlockArchiveWriter:141 - Total length of 0 blocks is 0 bytes
2022-09-24 06:29:16 INFO  Controller:427 - Validating blockchain
2022-09-24 06:29:16 INFO  BlockChain:668 - Couldn't retrieve block 2 from archive. Bootstrapping...
2022-09-24 06:29:16 INFO  Bootstrap:509 - Starting import of bootstrap...
2022-09-24 06:29:16 INFO  Bootstrap:384 - Downloading full node bootstrap from http://62.171.190.193/bootstrap-archive.7z ...
2022-09-24 06:29:21 INFO  Bootstrap:509 - Stopping repository...
2022-09-24 06:29:21 INFO  Bootstrap:509 - Deleting existing repository...
2022-09-24 06:29:21 INFO  Bootstrap:509 - Extracting bootstrap...
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 1
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 2
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 3
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 4
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 5
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 6
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 7
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 8
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 9
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 10
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 11
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 12
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 13
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 14
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 15
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 16
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 17
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 18
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 19
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 20
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 21
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 22
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 23
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 24
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 25
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 26
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 27
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 28
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 29
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 30
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:745 - Rebuilding AT state summaries in repository - this might take a while... (approx. 2 mins on high-spec)
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:756 - Rebuilding AT states height index in repository - this might take about 3x longer...
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:767 - Rebuilding AT state data in repository - this might take a while... (approx. 2 mins on high-spec)
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 31
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 32
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 33
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 34
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:834 - Altering AT table in repository - this might take a while... (approx. 20 seconds on high-spec)
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:847 - Adding index to AT states table...
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:855 - Altering AT states table in repository - this might take a while... (approx. 3 mins on high-spec)
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 35
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 36
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 37
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 38
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 39
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 40
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 41
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 42
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 43
2022-09-24 06:29:21 INFO  HSQLDBDatabaseUpdates:985 - HSQLDB repository updated to version 44
2022-09-24 06:29:21 WARN  HSQLDBRepository:270 - HSQLDBRepository.close() called when repository already closed. This is expected when bootstrapping.
2022-09-24 06:29:21 INFO  Bootstrap:326 - Bootstrap import failed
org.qortal.repository.DataException: Unable to import bootstrap
	at org.qortal.repository.Bootstrap.doImport(Bootstrap.java:345) ~[qortal.jar:3.6.0]
	at org.qortal.repository.Bootstrap.startImport(Bootstrap.java:322) [qortal.jar:3.6.0]
	at org.qortal.block.BlockChain.rebuildBlockchain(BlockChain.java:780) [qortal.jar:3.6.0]
	at org.qortal.block.BlockChain.validate(BlockChain.java:688) [qortal.jar:3.6.0]
	at org.qortal.controller.Controller.main(Controller.java:429) [qortal.jar:3.6.0]
Caused by: java.io.IOException: nextHeaderOffset is out of bounds
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.readStartHeader(SevenZFile.java:566) ~[qortal.jar:3.6.0]
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.readHeaders(SevenZFile.java:473) ~[qortal.jar:3.6.0]
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:343) ~[qortal.jar:3.6.0]
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:135) ~[qortal.jar:3.6.0]
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:376) ~[qortal.jar:3.6.0]
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:364) ~[qortal.jar:3.6.0]
	at org.qortal.utils.SevenZ.decompress(SevenZ.java:31) ~[qortal.jar:3.6.0]
	at org.qortal.repository.Bootstrap.importFromPath(Bootstrap.java:462) ~[qortal.jar:3.6.0]
	at org.qortal.repository.Bootstrap.doImport(Bootstrap.java:342) ~[qortal.jar:3.6.0]
	... 4 more
2022-09-24 06:29:21 INFO  Bootstrap:509 - Bootstrapping failed. Retrying in 1 minutes...
```

Without VPN it works perfectly. I do not have any blocking enabled in my VPN.

I **suspect** it is an issue with the core and not my VPN (other apps work fine with VPN).

**Comment by CalDescent1** [comment]
Interesting... it looks like the 7z archive must have been corrupt in some way, so failed to extract. I don't think I've seen this problem before. What VPN service were you using?

**Comment by Nuc1eoN** [comment]
My VPN service is https://windscribe.com/.

The good thing is, it is actually possible to use it for free afaik! (registration is required, but even giving email is optional)

So maybe you can simply download the client and see if you can reproduce?

> Interesting... it looks like the 7z archive must have been corrupt in some way, so failed to extract.

This happens very early in the process, so I am not sure it has even downloaded a 7z archive yet.

**Comment by QuickMythril** [comment]
Looking at the logs above, it only spent 5 seconds downloading.
That doesn't seem like enough time for the whole archive.
There are problems when bootstrapping over Tor as well.

It is possible to download and extract the files manually as a workaround:
https://wiki.qortal.org/doku.php?id=how_to_bootstrap_delete_the_db#manual_bootstrap

**Comment by QuickMythril** [comment]
to add some additional context to this, i have just successfully downloaded & extracted the bootstrap archive, and started the Core, while using IVPN.  i think we'd need to narrow down the issue to see exactly why the bootstrap server is having problems connecting to people over certain services.  it doesn't seem to be as simple as just blocking all VPNs.

**Comment by Nuc1eoN** [comment]
@QuickMythril You could try to reproduce it using Winscribe which I have used, it is a free VPN.
